on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Claude Code Base Action
        uses: anthropics/claude-code-base-action@v0.0.9

